# Base images
BASE_IMAGE=registry.access.redhat.com/ubi9/ubi:9.8@sha256:094ea2ecfd3225af8f93807b99daa9ff33710fc705ebdf6e8466f46ed605585c
RELEASE_BASE_IMAGE=registry.access.redhat.com/ubi9-minimal:9.8@1d7c5517a4a1a8e2688620b39ee980e82505ca1ab7ae5541b5463120ae9b3897

# Logging/tests
VERBOSE_LOGS=ON
RUN_TESTS=ON
CHECK_COVERAGE=0

# Distro/GPU
BASE_OS=redhat
GPU=1
ov_use_binary=0

# Versions / LTO
INSTALL_DRIVER_VERSION=24.52.32224
LTO_ENABLE=ON
LTO_CXX_FLAGS=-flto=auto -ffat-lto-objects -march=haswell
LTO_LD_FLAGS=-flto=auto -ffat-lto-objects -Wl,-plugin-opt=-march=haswell

# Source/branch
SOURCE=opendatahub-io
BRANCH=releases/2025/3
ov_source_org=opendatahub-io
ov_source_branch=releases/2025/3

# Parallelism
JOBS=12

# Bazel flags (no quotes, entire value after the '=')
debug_bazel_flags=--strip=always --define MEDIAPIPE_DISABLE=0 --define PYTHON_DISABLE=0 --//:distro=redhat --local_ram_resources=20480 --local_cpu_resources=16 --verbose_failures --subcommands --config=mp_on_py_on
CAPI_FLAGS=--strip=always --config=mp_off_py_off --//:distro=redhat --local_ram_resources=20480 --local_cpu_resources=16 --verbose_failures --subcommands
