apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/red-hat-data-services/openvino_model_server?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    build.appstudio.redhat.com/pull_request_number: "{{pull_request_number}}"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-comment: "^/build-konflux"
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
  labels:
    appstudio.openshift.io/application: automation
    appstudio.openshift.io/component: pull-request-pipelines-odh-openvino-model-server-v2-25
    pipelines.appstudio.openshift.io/type: build
  name: odh-openvino-model-server-v2-25-on-pull-request
  namespace: rhoai-tenant
spec:
  timeouts:
    pipeline: 8h
    tasks: 8h
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: additional-tags
    value:
    - 'pr-{{pull_request_number}}-into-{{target_branch}}'
  - name: additional-labels
    value:
    - version=on-pr-{{revision}}
    - io.openshift.tags=odh-openvino-model-server-v2-25
  - name: output-image
    value: quay.io/rhoai/pull-request-pipelines:odh-openvino-model-server-v2-25-{{revision}}
  - name: rhoai-version
    value: "2.25.2"
  - name: dockerfile
    value: Dockerfile.konflux
  - name: path-context
    value: .
  - name: hermetic
    value: false
  - name: build-source-image
    value: true
  - name: build-image-index
    value: true
  - name: fetch-git-tags
    value: true
  - name: clone-depth
    value: "2147483647"
  - name: build-platforms
    value:
    - linux-extra-fast/amd64
  - name: build-args-file
    value: .konflux/build-args.conf
  - name: image-expires-after
    value: 5d
  - name: enable-slack-failure-notification
    value: "false"
  taskRunSpecs:
    - pipelineTaskName: build-images
      stepSpecs:
        - name: build
          computeResources:
            requests:
              cpu: '8'
              memory: 16Gi
            limits:
              cpu: '16'
              memory: 32Gi
  pipelineRef:
    resolver: git
    params:
    - name: url
      value: https://github.com/red-hat-data-services/konflux-central.git
    - name: revision
      value: '{{ target_branch }}'
    - name: pathInRepo
      value: pipelines/multi-arch-container-build.yaml
  taskRunTemplate:
    serviceAccountName: build-pipeline-pull-request-pipelines
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
